### ISSUE TITLE
I want to break each PATH OPERATION into its own file

### ISSUE THREAD

**Issue by ericweidl** [mohsen1/multi-file-swagger-example#20]
The situation: my API has a public and a private version. The public version can basically only GET, the private version supports GET and POST.

My directory structure is:
```
/paths
    /foo
        get.yaml
        post.yaml
```
I want to be able to create index files which only include the appropriate paths for the particular API.

For example, for the public version of my API, my root index would be something like:

```--- 
swagger: '2.0'
info:
  description: The public API...
...
paths:
  $ref: ./paths/index-public.yaml
...
```

And the index for the private version of my API would be something like:

```---
swagger: '2.0'
info:
  description: The private API...
...
paths:
  $ref: ./paths/index-private.yaml
...
```
The corresponding files would then contain:

/paths/index-public.yaml:

```
/foo:
  $ref: ./foo/get.yaml
```

/paths/index-private.yaml:

```
/foo:
  $ref: ./foo/get.yaml
  $ref: ./foo/post.yaml
```

I get a "duplicate key" error when I use multi-file-swagger to bundle the private API. 

Can you give me any tips on how I can achieve my goal?

**Comment by mohsen1** [comment]
Have you thought about having two index entry points for public and private? It might be a bit more verbose that will work for sure:

```yml
#private index.yml
paths:
  /foo:
    $ref: ./foo/get.yaml
    $ref: ./foo/post.yaml
  /bar:
   # ...
````
```yml
#public index.yml
paths:
  /foo:
    $ref: ./foo/get.yaml
  /bar:
   # ...
````
